### ISSUE TITLE
Plugin Won't Start, Fails with TypeError: Cannot read property line_1 of undefined

### ISSUE THREAD

**Issue by sinkr** [valiquette/homebridge-orbit-irrigation#22]
Plugin Version: v1.1.3
Homebridge Version: 1.3.9
OS: Ubuntu 20.04.03 LTS
Node Version: 15.14.0
Orbit Hub (gen 2) version: BH1G2-0001 **I just realized this hub is not explicitly supported.**

Error (with or without address _locationAddress_ set to the address in the B-Hyve Hub or removed completely from the config JSON):
`[1/17/2022, 5:06:16 PM] [B-Hyve] Failed to get token TypeError: Cannot read property 'line_1' of undefined
    at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:77:148
    at Array.filter (<anonymous>)
    at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:73:25
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

Thanks for the plugin and any assistance!

**Comment by valiquette** [comment]
I was able to reproduce this, it is a use case I had not expected. The root cause it that there is no address defined in your B-Hyve account. You can check you app or the web site. In their app only the zip code is required the rest of the location address is listed as optional. I am certain that if you put any address in their app this plugin will load. That said it is optional so I have addressed this use case in the plugin and will publish an update shortly. Thanks and do let me know if the hardware works and I'll add it to the list of verified hardware.

**Comment by sinkr** [comment]
Thank you for the response.  There was an address defined in my account for the hub, and the irrigation devices, but I went back through and verified that the hub's address, fully populated, matched each of the irrigation devices.

I upgraded to v1.1.4 of your plugin and seem to have gotten farther, however, I get this error now (address matches, but redacted for the post here):
```
  1 1/17/2022, 9:24:23 PM] [B-Hyve] Adding online BH1G2-0001 device Main found at the configured location: 123 Main St
  2   [1/17/2022, 9:24:23 PM] [B-Hyve] Skipping fs1-0001 device Under Stairs At Sump Pump at undefined location, not found at the configured location: 123 Main St
  3 [1/17/2022, 9:24:23 PM] [B-Hyve] Adding online HT31-0001 device Back 2 found at the configured location: 123 Main St
  4 [1/17/2022, 9:24:23 PM] [B-Hyve] Failed to get token TypeError: Cannot read property 'run_mode' of undefined
  5 | | at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:101:93
  6 | | at Array.forEach (<anonymous>)
  7 | | at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:99:14
  8 | | at processTicksAndRejections (node:internal/process/task_queues:94:5)
  9 [1/17/2022, 9:24:24 PM] [TuyaWebPlatform] Missing required `id` property on device configuration, received:
 10 {
 11 | "device_type": "form"
 12 }
 ```

You will notice that the address reported by the plugin on line 1 matches that of the HT31-0001 irrigation device, which successfully adds and is online, but we get the ensuing _run_mode_ error further on down.

You'll also notice a flood sensor in there, which I'm not expecting to work at this time.

Let me know how I can help!

**Comment by valiquette** [comment]
Interesting, I see the FS1-0001, I will have no support for that at this time, but possible in the future. I see that one as not having an address, maybe by design.
I am suspecting that the BH1G2-0001 has a different response structure than the BH1-0001. This response is captured in the debug log.  Would you be able to enable the homebridge debug log.
then look for the line that looks like
[1/18/2022, 10:05:37 AM] [B-Hyve-Dev] get devices response [ 
.....looking for the data between these 2 lines (it is a lot of lines)
[1/18/2022, 10:05:37 AM] [B-Hyve-Dev] Adding online BH1-0001 device B-Hyve found at the configured location: 123 Main St
You can sanitize what you like right of any : if you want I am only interested in the structure and will delete it once I have it.

**Comment by valiquette** [comment]
I did publish a beta version 1.1.5 which you can find in previous versions. This beta is attempting to support the new bridge and new hose timer versions. I added a config option to show the flood sensor, I can't test it so no idea what it will do.

**Comment by sinkr** [comment]
I was just getting ready to enable debug logging when this popped up.  I installed 1.1.5 beta and I no longer get the errors above, however, I cannot control the new irrigation unit or the older one from HomeKit, but I can control them from the B-Hyve app.

The flood sensors don't show up and to answer an earlier question of yours, the app does not have a field for an address location for the flood sensors. 

Here's what my logs (not in debug mode) look like now:

```
[1/19/2022, 3:14:54 PM] [B-Hyve] Online device BH1G2-0001 Main found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Under Stairs At Sump Pump at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Storage Room At Water Heater at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Under Kitchen Sink at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Offline device HT25-0000 Back 1 found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Offline device HT25-0000 Front 1 found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Offline device HT25-0000 Garage 1 found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Online device HT31-0001 Back 2 found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Offline device HT25-0000 Front 2 found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Offline device HT25-0000 Garage 2 found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Powder Room Behind Sink at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Washing Machine at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Basement Bathroom Behind Sink at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 Guest Bathroom Beside Sink at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping device fs1-0001 MBR Robert’s Sink at undefined location, not found at the configured location: 123 Main St
[1/19/2022, 3:14:54 PM] [B-Hyve] Skipping Bridge
[1/19/2022, 3:14:54 PM] [B-Hyve] Back 1 disconnected at undefined This will show as non-responding in Homekit until the connection is restored
[1/19/2022, 3:14:54 PM] [B-Hyve] Configure Irrigation system for Back 1
[1/19/2022, 3:14:54 PM] [B-Hyve] Configured zone-1 for  with 60 min runtime
[1/19/2022, 3:14:54 PM] [B-Hyve] Front 1 disconnected at undefined This will show as non-responding in Homekit until the connection is restored
[1/19/2022, 3:14:54 PM] [B-Hyve] Configure Irrigation system for Front 1
[1/19/2022, 3:14:54 PM] [B-Hyve] Configured zone-1 for  with 60 min runtime
[1/19/2022, 3:14:54 PM] [B-Hyve] Garage 1 disconnected at undefined This will show as non-responding in Homekit until the connection is restored
[1/19/2022, 3:14:54 PM] [B-Hyve] Configure Irrigation system for Garage 1
[1/19/2022, 3:14:54 PM] [B-Hyve] Configured zone-1 for  with 60 min runtime
[1/19/2022, 3:14:54 PM] [B-Hyve] Configure Irrigation system for Back 2
[1/19/2022, 3:14:54 PM] [B-Hyve] Adding Battery status for Back 2
[1/19/2022, 3:14:54 PM] [B-Hyve] Configured zone-1 for  with 60 min runtime
[1/19/2022, 3:14:54 PM] [B-Hyve] Front 2 disconnected at undefined This will show as non-responding in Homekit until the connection is restored
[1/19/2022, 3:14:54 PM] [B-Hyve] Configure Irrigation system for Front 2
[1/19/2022, 3:14:54 PM] [B-Hyve] Configured zone-1 for  with 60 min runtime
[1/19/2022, 3:14:54 PM] [B-Hyve] Garage 2 disconnected at undefined This will show as non-responding in Homekit until the connection is restored
[1/19/2022, 3:14:54 PM] [B-Hyve] Configure Irrigation system for Garage 2
[1/19/2022, 3:14:54 PM] [B-Hyve] Configured zone-1 for  with 60 min runtime
[1/19/2022, 3:16:35 PM] [B-Hyve] Starting zone-1  for 60 mins
[1/19/2022, 3:16:35 PM] [B-Hyve] Stopping Zone
```

Again, thanks so much for the plugin and the help.  The good news here on the east coast is that watering season is months away!  :)

**Comment by valiquette** [comment]
The debug log would be very helpful. I am interested in the flood sensors I will have to get my hands on some and I'll get that worked out at some point.

**Comment by sinkr** [comment]
Actually. the new device, the HT31-0001 (Back 2) does work.  

I cannot seem to get the HT25-0001 (Back 1) to work, despite it being reachable via the B-Hyve app.

I will get the debug logging going now.

**Comment by sinkr** [comment]
OK, I'm apparently missing something.  I update /etc/default/homebridge, HOMEBRIDGE_OPTS to "-D" and "-D DEBUG," restarted via systemctl (and hb-service), yet the logs look the same to me in the console and on disk in /var/lib/homebridge.

What am I doing wrong?

**Comment by valiquette** [comment]
can you enable it in the GUI?  the 3 dot in the top right hand corner under Homebridge settings ?

**Comment by sinkr** [comment]
Oh, that was too simple; I wasn't expecting that!
[hb.log](https://github.com/valiquette/homebridge-orbit-irrigation/files/7900649/hb.log)

**Comment by valiquette** [comment]
got it, I will take a look. Your question about back1, the App can connect over Bluetooth and may be different.
Did you upgrade from the Gen 1 hub to the Gen 2 hub? have you reset your connection?

**Comment by sinkr** [comment]
Yes, the gen1 hub has been replaced by the gen2 and all the devices were re-paired to the gen2 previously.  My guess is, the flood sensors use BLE, hence the new hub.

The new version of the iOS app has removed the option under Devices -> Device Name to connect via Bluetooth, so it's not apparent to me if it's using BT or not.  When I go into iPhone Settings -> Bluetooth, I don't see the B-Hyve connected.

I did reset the BT25-0001's connection via the app, it reconnected there and I restarted Homebridge for good measure, but no luck.

This is the event I get to the failed connection of the BT25-0001:

```
1/19/2022, 5:09:29 PM] [B-Hyve] {
  source: 'local',
  event: 'watering_in_progress_notification',
  program: 'manual',
  current_station: 1,
  run_time: 60,
  started_watering_station_at: '2022-01-19T22:09:29.279Z',
  rain_sensor_hold: false,
  device_id: '<redacted>',
  timestamp: '2022-01-19T22:09:29.279Z'
}
[1/19/2022, 5:09:29 PM] [B-Hyve] Simulating websocket event for <redacted> will update services
[1/19/2022, 5:09:29 PM] [B-Hyve] <redacted> sending {
  "event": "change_mode",
  "mode": "manual",
  "device_id": "<redacted>",
  "stations": [
    {
      "station": 1,
      "run_time": 60
    }
  ]
```

**Comment by valiquette** [comment]
I notice a number of lines just missing or null in the log file for the HT25s yet they are there for the HT35.
like battery, status and is connected. I am not sure why that would be other than being out of sync.
FYI the only IDs you really need to redact ar the user ID and API key, the device ID are fine. Can you check out this site https://techsupport.orbitbhyve.com it should see a lot of the same things the plugin sees, I would expect you to see battery status and run mode. You can repair connection and sync from there. You may find it helpful

**Comment by valiquette** [comment]
I expect you may see some errors

**Comment by sinkr** [comment]
This is all very helpful!  TIL that the HT25s apparently only want to pair with the previous version of the hub, the BH1-001.

**Comment by valiquette** [comment]
No problem I hope things are working once you moved the Gen 1 timers back to a Gen 1 hub? I did read that this is the case on the Orbit site, seem odd but... I ordered some flood sensors, I have a real good use case for them where freezing pipes are a problem and nice that they have temp includes. you can look at beta.2. The sensors should show up, they won't actually response yet.

**Comment by sinkr** [comment]
Yep, the gen 1 timers work now on the gen1 hub.   The flood sensors seem to work pretty well for my testing and I've had pretty much everything burst, overflow, or leak that's possible in this house, so I'm putting them everywhere near water.  :)

Beta 2 shows the sensors and temperatures, which is very cool!

**Comment by valiquette** [comment]
Version 1.2 should have addressed any remaining open issues. Thanks for the feedback
