### ISSUE TITLE
Won't show up as irrigation device on HomeKit

### ISSUE THREAD

**Issue by edgarfebres** [valiquette/homebridge-orbit-irrigation#4]
[11/5/2021, 11:02:39 PM] [Orbit B-Hyve] Adding device Alcatraz found at the configured location: _<partial address here>_
[11/5/2021, 11:02:39 PM] [Orbit B-Hyve] Adding Sprinkler Timer
[11/5/2021, 11:02:39 PM] [Orbit B-Hyve] Configure Irrigation service for Alcatraz
[11/5/2021, 11:02:39 PM] [Orbit B-Hyve] Failed to get token TypeError: Cannot read property 'percent' of null
    at PlatformOrbit.createBatteryService (/usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:341:67)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:93:41
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:73:14
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by valiquette** [comment]
Is this device the hose timer? Can for you to turn on debug logs and send the output for when this happens?

**Comment by valiquette** [comment]
I am guessing that you may have some Orbit hardware maybe without a battery that I am not able to test against at this time. I have only tested against the HT-25 with a BH1 bridge. Short of having the debug logs to see exactly what is being returned for device info, I have published a beta version that will not try and configure a battery service if it does not detect an entry for a battery. Let me no if the beta version corrects this for you. If you are using something other than the Hose Timer and want to send me the debug logs it would be helpful.
