### ISSUE TITLE
Error getting API

### ISSUE THREAD

**Issue by jbuttnz** [valiquette/homebridge-orbit-irrigation#54]
Getting the following error, and ideas?

Using hub 96506 which is the Australia/Europe version of the BH1.

[2/16/2023, 8:54:31 PM] [B-Hyve] Error getting API key Request failed with status code 401
[2/16/2023, 8:54:31 PM] [B-Hyve] {
  "message": "not authorized"
}
[2/16/2023, 8:54:31 PM] [B-Hyve] Error retrieving API key TypeError: Cannot read properties of undefined (reading 'data')
    at OrbitAPI.getToken (/homebridge/node_modules/homebridge-orbit-irrigation/orbitapi.js:47:69)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PlatformOrbit.getDevices (/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:75:24)
[2/16/2023, 8:54:31 PM] [B-Hyve] Failed to get devices...TypeError: Cannot read properties of undefined (reading 'data')
    at PlatformOrbit.getDevices (/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:75:147)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by valiquette** [comment]
The error indicates your user name or password is not correct in the plugins config. You can verify it at https://techsupport.orbitbhyve.com/login 

Make sure there is no white space in either, which can happen with a copy paste

**Comment by jbuttnz** [comment]
That was it! Bit embarrassing but glad it was an easy fix. Thank you.

**Comment by jbuttnz** [comment]
That was it! Bit embarrassing but glad it was an easy fix. Thank you.
