### ISSUE TITLE
Unable to get B-Hyve API Token Error 

### ISSUE THREAD

**Issue by NPSconsultingLLC** [valiquette/homebridge-orbit-irrigation#59]
After the latest update I a not able to activate my smart hose timers via the HomeKit app (using home bridge). 

In the logs I see the following error message 

`[5/27/2023, 11:40:54 AM] [B-Hyve] Error retrieving API key 
TypeError: axios is not a function
    at OrbitAPI.getToken (/homebridge/node_modules/homebridge-orbit-irrigation/orbitapi.js:26:25)
    at PlatformOrbit.getDevices (/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:81:44)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:418:11)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
[5/27/2023, 11:40:54 AM] [B-Hyve] Failed to get devices. Retry attempt 2 of 3 in 60 seconds...`

I have validated that my login is correct (and I am able toes my devices are online via the B-Hyve app. Not sure how to debug this further would like some help

**Comment by valiquette** [comment]
can you send me a copy of this plugins config?

**Comment by valiquette** [comment]
wha tis the error after the 3rd try?

**Comment by valiquette** [comment]
This would appear to be an issue with your setup have you tried restarting thing, if it still is an issue let me know what platform and version you are running. maybe update again.

**Comment by valiquette** [comment]
no activity
