### ISSUE TITLE
HT32-0001 error (others just like it work fine)

### ISSUE THREAD

**Issue by sinkr** [valiquette/homebridge-orbit-irrigation#75]
Hello, thank you for this plugin!

Plugin Version: v1.2.23 
HomeBridge Version: 1.6.1
NodeJS Version: v18.16.1 

I have a perplexing situation, I have multiple of the above-mentioned timers, however, this one timer does not show up in HomeKit.  When I activate it from the B-Hyve app, the debug logs in HomeBridge give this error:

```
Error updating service TypeError: Cannot read properties of undefined (reading 'getService')
    at PlatformOrbit.updateService (/usr/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:649:51)
    at /usr/lib/node_modules/homebridge-orbit-irrigation/orbitapi.js:363:6
    at ReconnectingWebSocket._callEventListener (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:557:13)
    at /usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:81
    at Array.forEach (<anonymous>)
    at WebSocket.ReconnectingWebSocket._handleMessage (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:38)
    at callListener (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Receiver.Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.socketOnData (/usr/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:1278:35)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by sinkr** [comment]
PEBKAC--my street address did not match.
