### ISSUE TITLE
Childe Bridge Restarting Homebridge

### ISSUE THREAD

**Issue by amashragi** [valiquette/homebridge-orbit-irrigation#83]
I updated to Node 20 and now the plugin constantly restarts the homebridge. Tried running it as a child bridge and the same issue. Any reason?

**Comment by valiquette** [comment]
I have no issue with this running on node 20. You would have to provide a more information if you think this is tied to the plugin (platform, versions...). What happens if you roll back to 18?

**Comment by amashragi** [comment]
running homebridge-orbit-irrigation v1.2.27, node v20.9.0 on homebridge-config-ui-x v4.52.3.

**Comment by valiquette** [comment]
Can you provide any logging prior to the restart?

**Comment by vascott1** [comment]
I see this is still open and just started happening to me. I updated my NAS so docker restarted but I have not made any updates to Node.  Here is the info from my system that was requested earlier for the previous reporter:

Log entires showing the error:

[11/9/2024, 9:57:51 PM] [B-Hyve] Launched child bridge with PID 881
[11/9/2024, 9:57:51 PM] The plugin "homebridge-orbit-irrigation" requires Node.js version of ^18.20.0 || ^20.17.0 || ^22.9.0 which does not satisfy the current Node.js version of v20.15.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[11/9/2024, 9:57:51 PM] Registering platform 'homebridge-orbit-irrigation.bhyve'
[11/9/2024, 9:57:51 PM] [B-Hyve] Loaded homebridge-orbit-irrigation v1.2.36 child bridge successfully
[11/9/2024, 9:57:51 PM] Loaded 3 cached accessories from cachedAccessories.0E6B56CBE263.
[11/9/2024, 9:57:51 PM] [B-Hyve] Starting Orbit Platform using homebridge API 2.7
[11/9/2024, 9:57:51 PM] [B-Hyve] Getting Account info...
Error: listen EADDRINUSE: address already in use :::59154
    at Server.setupListenHandle [as _listen2] (node:net:1898:16)
    at listenInCluster (node:net:1946:12)
    at Server.listen (node:net:2044:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:166:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:380:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1378:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:196:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:177:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:170:75
    at new Promise (<anonymous>)
[11/9/2024, 9:57:51 PM] [B-Hyve] Child bridge process ended
[11/9/2024, 9:57:51 PM] [B-Hyve] Process Ended. Code: 1, Signal: null
[11/9/2024, 9:57:57 PM] [B-Hyve] Stopping child bridge (will not restart)...

config.json for the plugin:

{
    "name": "B-Hyve",
    "email": "xxxx@gmail.com",
    "password": "xxxx",
    "defaultRuntime": 1,
    "runtimeSource": 0,
    "useIrrigationDisplay": true,
    "showSimpleValve": true,
    "displayValveType": 1,
    "showIrrigation": true,
    "showBridge": false,
    "showFloodSensor": false,
    "showTempSensor": false,
    "showLimitsSensor": false,
    "showStandby": false,
    "showRunall": false,
    "showSchedules": false,
    "showAPIMessages": true,
    "showIncomingMessages": true,
    "showOutgoingMessages": true,
    "_bridge": {
        "username": "0E:6B:56:CB:E2:63",
        "port": 59154
    },
    "platform": "bhyve"
}

**Comment by valiquette** [comment]
this error seem level higher than the plugin. can you double check the docker environment, not sure why the children sport is already in use. The node version is just a warning. I guess out could try removing the child bridge and add it back with a new port.
