### ISSUE TITLE
This plugin generated a warning from the characteristic 'Model'

### ISSUE THREAD

**Issue by arcticgenes** [valiquette/homebridge-orbit-irrigation#85]
Getting the following message in my homebridge logs everytime homebridge restarts.

[19/05/2024, 10:51:18] [homebridge-orbit-irrigation] This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.

**Comment by valiquette** [comment]
What model device are you using that generates this message?

**Comment by arcticgenes** [comment]
Your friend has shared a link to a Home Depot product they think you would
be interested in seeing.
https://www.homedepot.com/p/Orbit-B-hyve-Bluetooth-Add-On-Hose-Watering-Timer-Sprinkler-Timer-21005/305079377


Aaron Lewis

**Comment by everydaylearner** [comment]
I am getting same error as well. It is crashing homebridge. I am using the following device;
https://www.homedepot.com/p/Orbit-B-hyve-12-Zone-Indoor-Outdoor-Smart-Sprinkler-Controller-Works-with-Amazon-Alexa-57950/206638406

and have this one as well
https://www.homedepot.com/p/Orbit-B-hyve-Bluetooth-Add-On-Hose-Watering-Timer-Sprinkler-Timer-21005/305079377

Thank you!

**Comment by valiquette** [comment]
I am not sure about the zone controller it would be good to know the hardware version to see if this one has been tested. 
As for the model warning, it would seem the response you're getting back from B-Hyve has some missing data.  I could handle this and avoid the warning in the future but it would not address the why. 

If you can go to 
https://techsupport.orbitbhyve.com
login and make sure things look ok this is a little more functional than the app.
note the device type your controller reports as.

Second 
If you can enable debug logging in homebridge settings and in the plugin config enable log API response under debug logging.

You should see something like for each device this when the plug-in first starts up, the value for the hardware version is used for the model in the plugin.

attach a sanitized response of the debug log for a plugin restart.

  "devices": [
    {
      "location_name": null,
      "address": {
        "line_1": "somewhere",
        "city": "anywhere",
        "state": "xx",
        "postal_code": "12345",
        "country": "US"
      },
      "firmware_version": "0030",
      "name": "Wi-Fi Hub",
      "type": "bridge",
      "mac_address": "446755271902",
      "mesh_id": "61353e044f0c6f063b7f2a76",
      "id": "61354e034f0c6f063b7f2a74",
      "hardware_version": "BH1-0001",
      "is_connected": true
    },

**Comment by arcticgenes** [comment]
hardware versions in the support page are:

BH1-0001 - bluetooth hub
HT25-0000 - sprinkler controller


get device response {
  "last_connected_at": "2024-05-17T15:25:23.981Z",
  "address": {
    "line_1": “xxxxxxxx",
    "city": “xxxx”,
    "state": “xx”,
    "postal_code": “xxxx”,
    "country": "US"
  },
  "firmware_version": "0041",
  "name": "Patio Drip",
  "type": "sprinkler_timer",
  "restricted_frequency": null,
  "updated_at": "2024-05-18T07:38:29.098Z",
  "reference": "446755297543-57708",
  "mac_address": "446755528053",
  "weather_station_id": "5a3026324f0c3eb98b805d22",
  "mesh_id": "64b038e85ad8c1387160a5df",
  "device_gateway_topic": "devices-9",
  "smart_watering_enabled": true,
  "hardware_version": "HT25-0000",
  "is_connected": true,
  "created_at": "2023-07-23T01:20:50.022Z",
  "suggested_start_time": null,
}

**Comment by arcticgenes** [comment]
seems like the value of hardware_version would suffice for model

**Comment by valiquette** [comment]
and you still see this warning 
This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined

**Comment by valiquette** [comment]
if this was working fine recently, did something change? Silly question but I can't reproduce this with the same the same timer.

**Comment by arcticgenes** [comment]
Homebridge - 1.8.2
node js - 20.13.1

**Comment by everydaylearner** [comment]
> if this was working fine recently, did something change? Silly question but I can't reproduce this with the same the same timer.

i recently added new device - "HT25-0000" but i had old one registered in the past as well without any issue! but i cant recall if it started right after that! i believe that was not the case. I wonder if something changed on the Orbit Side maybe API update etc?

**Comment by valiquette** [comment]
Log was very helpful, In response to the warning I think I know wha tis going on and I can correct that one. 
take a look at the get device response in the log look for   sprinkler_type: 'spray',, if this is null that is the error I 

You can edit the zone info on the  web site https://techsupport.orbitbhyve.com/


[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] Configure Irrigation system for Front Porch
[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] Adding Battery status for Front Porch
[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] create battery service for Front Porch
[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] configured battery service for Front Porch
[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] adding zone Front Flowers
[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] {
  station: 1,
  slope_grade: 0,
  sun_shade: 'full_sun',
  name: 'Front Flowers',
  landscape_type: 'cool_season_turf',
  drought_level: null,
  num_sprinklers: 2,
  soil_type: 'clay',
  catch_cup_volumes: [],
  catch_cup_run_time: 0,
  smart_watering_enabled: false,
  sprinkler_type: 'spray',
  flow_data: {},
  enabled: true
}
[5/22/2024, 11:16:35 AM] [B-Hyve-Dev] Created valve service for Front Flowers with zone-id 1 with 60 sec runtime (1 min)

**Comment by arcticgenes** [comment]
how would sprinkler_type being empty cause the issue?  Your code is already using hardware_version to set the characteristic of model.

**Comment by valiquette** [comment]
have you tried removing the cached accessory for this one?, I know if could remove it from homekit but it might be worth trying.

**Comment by arcticgenes** [comment]
re-ran the debug and despite having a sprinkler_type setup in in my zone on the webpage, the API isn't getting that key/value in the json and thus it is missing when creating the valve service.

[22/05/2024, 12:17:31] [B-Hyve] Update valve accessory 64bbe43b5ad8c138717be13d station-1 Succulent Drip
[22/05/2024, 12:17:31] [B-Hyve] {
  station: 1,
  name: 'Succulent Drip',
  num_sprinklers: 0,
  catch_cup_volumes: [],
  catch_cup_run_time: 0,
  smart_watering_enabled: false,
  enabled: true
}
[22/05/2024, 12:17:31] [B-Hyve] Created valve service for Succulent Drip with zone-id 1 with 120 sec runtime (2 min)
[22/05/2024, 12:17:31] [homebridge-orbit-irrigation] This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.

![Screenshot 2024-05-22 at 12 50 20 PM](https://github.com/valiquette/homebridge-orbit-irrigation/assets/15093622/7e15e47c-967b-4456-81d4-dad9eb6f2bf2)

**Comment by valiquette** [comment]
Issue should be addressed in the latest update

**Comment by aaron-lewis-insight** [comment]
installed the newest version and now homebridge is crashing

[19/06/2024, 06:40:59] [B-Hyve] Adding Battery status for Succulent Drip
[19/06/2024, 06:41:07] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[19/06/2024, 06:41:08] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:539:22)
    at ReconnectingWebSocket._handleError (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:14)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[19/06/2024, 06:41:08] [B-Hyve] Opps ErrorEvent {
  target: ReconnectingWebSocket {
    _listeners: { error: [], message: [Array], open: [], close: [] },
    _retryCount: 1,
    _shouldReconnect: true,
    _connectLock: true,
    _binaryType: 'blob',
    _closeCalled: false,
    _messageQueue: [
      '{\n' +
        '  "name": "Planter 3 Suc Fence",\n' +
        '  "id": "64b0401509fd9a1e9557876f",\n' +
        '  "event": "app_connection",\n' +
        '  "orbit_session_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJ1c2VyLWlkIjoiNjRiMDM4OGY0MThmZTcyY2UzZGQ4OWQ5IiwiYXBwLWlkIjoiQmh5dmUgRGFzaGJvYXJkIn0.13rUemtDYCHAkhQdirmMcpUAg-CC5SUK8riYGM7VArw"\n' +
        '}'
    ],
    onclose: [Function (anonymous)],
    onerror: [Function (anonymous)],
    onmessage: [Function (anonymous)],
    onopen: [Function (anonymous)],
    _handleOpen: [Function (anonymous)],
    _handleMessage: [Function (anonymous)],
    _handleError: [Function (anonymous)],
    _handleClose: [Function (anonymous)],
    _url: 'wss://api.orbitbhyve.com/v1/events',
    _protocols: [],
    _options: {
      WebSocket: [Function],
      maxReconnectionDelay: 10000,
      minReconnectionDelay: 2804.173849918226,
      reconnectionDelayGrowFactor: 1.3,
      minUptime: 5000,
      connectionTimeout: 4000,
      maxRetries: Infinity,
      maxEnqueuedMessages: 1,
      startClosed: false,
      debug: false
    },
    send: [Function (anonymous)],
    _ws: WebSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: <Buffer >,
      _closeTimer: null,
      _extensions: {},
      _paused: false,
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _autoPong: true,
      _url: 'wss://api.orbitbhyve.com/v1/events',
      _req: [ClientRequest],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    _connectTimeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 39512,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 2884,
      [Symbol(triggerId)]: 0
    }
  },
  type: 'error',
  message: 'TIMEOUT',
  error: Error: TIMEOUT
      at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
      at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)
}
[19/06/2024, 06:41:08] TypeError: Cannot read properties of undefined (reading 'send')
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitapi.js:342:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by valiquette** [comment]
Is this crashing every time?

**Comment by aaron-lewis-insight** [comment]
yup, crashes, restarts, and crashes in a constant loop until plugin is disabled.

**Comment by valiquette** [comment]
I am concerned about this line
[19/06/2024, 06:41:07] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38 

and why the name is empty

**Comment by valiquette** [comment]
Rolling back to the previous version is OK?

**Comment by valiquette** [comment]
I was able to replicate this. The plugin is expecting all zones to be named, in your case it appears that is not the case. It does seem a little odd that a device with one zone can have a device name and a zone name, but. The plugin will now detect this and warn of the condition and use the device name. let me know if this corrects your issue.

**Comment by aaron-lewis-insight** [comment]
Everything seems happy now.  Thank you for the quick turnaround.

**Comment by arcticgenes** [comment]
updated to the latest version and noticed that intermittently on reboot this error pops up and crashes homebridge.  It seems like it works sometimes but it would be nice if this error didn't crash homebridge at all

[19/06/2024, 16:21:07] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:292:7)
    at ReconnectingWebSocket._disconnect (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:539:22)
    at ReconnectingWebSocket._handleError (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:14)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[19/06/2024, 16:21:07] [B-Hyve] Opps ErrorEvent {
  target: ReconnectingWebSocket {
    _listeners: { error: [], message: [Array], open: [], close: [] },
    _retryCount: 1,
    _shouldReconnect: true,
    _connectLock: true,
    _binaryType: 'blob',
    _closeCalled: false,
    _messageQueue: [
      '{\n' +
        '  "name": "Planter 4",\n' +
        '  "id": "64b34e613080dc4ae0160ef5",\n' +
        '  "event": "app_connection",\n' +
        '  "orbit_session_token": "removed by me"\n' +
        '}'
    ],
    onclose: [Function (anonymous)],
    onerror: [Function (anonymous)],
    onmessage: [Function (anonymous)],
    onopen: [Function (anonymous)],
    _handleOpen: [Function (anonymous)],
    _handleMessage: [Function (anonymous)],
    _handleError: [Function (anonymous)],
    _handleClose: [Function (anonymous)],
    _url: 'wss://api.orbitbhyve.com/v1/events',
    _protocols: [],
    _options: {
      WebSocket: [Function],
      maxReconnectionDelay: 10000,
      minReconnectionDelay: 3768.465040969599,
      reconnectionDelayGrowFactor: 1.3,
      minUptime: 5000,
      connectionTimeout: 4000,
      maxRetries: Infinity,
      maxEnqueuedMessages: 1,
      startClosed: false,
      debug: false
    },
    send: [Function (anonymous)],
    _ws: WebSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: <Buffer >,
      _closeTimer: null,
      _extensions: {},
      _paused: false,
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _autoPong: true,
      _url: 'wss://api.orbitbhyve.com/v1/events',
      _req: [ClientRequest],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    _connectTimeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 48500,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 3307,
      [Symbol(triggerId)]: 0
    }
  },
  type: 'error',
  message: 'TIMEOUT',
  error: Error: TIMEOUT
      at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
      at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)
}
[19/06/2024, 16:21:07] TypeError: Cannot read properties of undefined (reading 'send')
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitapi.js:342:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
