### ISSUE TITLE
Watering status doesn't return to off in HomeKit after use

### ISSUE THREAD

**Issue by jase-melbourne** [valiquette/homebridge-orbit-irrigation#9]
Loving the plugin, but I have an odd bit of behaviour whereby the watering status turns to on in both the homebridge accessories view and in HomeKit, but when watering stops it turns off in homebridge but stays on in HomeKit.  I also get this error multiple times, which I think coincides with it trying to turn watering off:

[04/12/2021, 11:25:22] [B-Hyve] Error updating service TypeError: Cannot read property 'devices' of undefined
    at PlatformOrbit.updateService (/usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:633:39)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitapi.js:253:17
    at ReconnectingWebSocket._callEventListener (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:557:13)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:81
    at Array.forEach (<anonymous>)
    at WebSocket.ReconnectingWebSocket._handleMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:38)
    at WebSocket.onMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:1008:20)
    at Receiver.emit (events.js:400:28)

**Comment by jase-melbourne** [comment]
Also, whilst running, the system shows as "running" but the valve (only 1 connected at the moment" stays in "Waiting" status.

[04/12/2021, 12:54:17] [B-Hyve] Starting zone-1 Hyve Water Timer for 10 mins
[04/12/2021, 12:54:17] [B-Hyve] Error updating service TypeError: Cannot read property 'devices' of undefined
    at PlatformOrbit.updateService (/usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:633:39)
    at PlatformOrbit.setValveValue (/usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:480:12)
    at Active.emit (events.js:400:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1668:16
    at new Promise (<anonymous>)
    at Active.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1666:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
[04/12/2021, 12:54:18] [B-Hyve] Error updating service TypeError: Cannot read property 'devices' of undefined
    at PlatformOrbit.updateService (/usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:633:39)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitapi.js:253:17
    at ReconnectingWebSocket._callEventListener (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:557:13)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:81
    at Array.forEach (<anonymous>)
    at WebSocket.ReconnectingWebSocket._handleMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:38)
    at WebSocket.onMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:1008:20)
    at Receiver.emit (events.js:400:28)
[04/12/2021, 12:54:18] [B-Hyve] Error updating service TypeError: Cannot read property 'devices' of undefined
    at PlatformOrbit.updateService (/usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitplatform.js:633:39)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/orbitapi.js:253:17
    at ReconnectingWebSocket._callEventListener (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:557:13)
    at /usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:81
    at Array.forEach (<anonymous>)
    at WebSocket.ReconnectingWebSocket._handleMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:176:38)
    at WebSocket.onMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:1008:20)
    at Receiver.emit (events.js:400:28
![IMG_0621](https://user-images.githubusercontent.com/95510918/144692695-a03d71bd-6281-4ca5-9932-6e2bc54b3549.PNG)
)

**Comment by valiquette** [comment]
what version of the plugin are you running? would you mind sending me the plugins configuration, minus your account info?

**Comment by jase-melbourne** [comment]
I'm running the latest version - 1.0.6.  

Config is as follows:

{
            "name": "B-Hyve",
            "email": "XXX",
            "password": "XXX",
            "defaultRuntime": 10,
            "useIrrigationDisplay": true,
            "displayValveType": 0,
            "showBridge": false,
            "showStandby": false,
            "showRunall": false,
            "showSchedules": false,
            "platform": "bhyve"

**Comment by valiquette** [comment]
is this new with the last update or has it been there a while?

**Comment by jase-melbourne** [comment]
I only installed it for the first time yesterday as my irrigation was setup.  I never tried it on earlier versions so not sure.  Should I try going back to the previous version?

**Comment by valiquette** [comment]
no, give me a bit to look into it. if you like you could pass along the debug log following a restart to the error

**Comment by jase-melbourne** [comment]
Sure can!  Sorry I'm new to homebridge - where is the debug log kept?

**Comment by jase-melbourne** [comment]
[homebridge.log.txt](https://github.com/valiquette/homebridge-orbit-irrigation/files/7653164/homebridge.log.txt)

**Comment by jase-melbourne** [comment]
[homebridge.log.txt](https://github.com/valiquette/homebridge-orbit-irrigation/files/7653165/homebridge.log.txt)

Is it this?

**Comment by valiquette** [comment]
that is the log, but you can enable additional debug logging in the Homebridge setting, (3 vertical dots upper right).
The issue, is this plugging has only been tested against the hose timer (HT-25) and you have a water timer (WT-25).  The error on the plugging is it is expecting a battery and the WT does not have one, I assume you also have more than one zone too. I thought I addressed this possibility but without a test case but maybe not. I should be able to support this WT device pretty easy, I just need the debug logs to validate.

**Comment by jase-melbourne** [comment]
[homebridge.log.txt](https://github.com/valiquette/homebridge-orbit-irrigation/files/7654707/homebridge.log.txt)

Ah I see! The unit is mains powered with a battery backup for the panel.  I only have 1 zone configured at the moment but there will be multiple zones once it's finished.  I've attached the debug logs as requested. It would be awesome if you can get it to work!

**Comment by valiquette** [comment]
I have published a beta version for you to try, you can find it under previous versions. Let me know if it clears up your errors.

**Comment by jase-melbourne** [comment]
That's amazing!  Thanks heaps.  I'll try it out tonight and let you know how it goes.

**Comment by jase-melbourne** [comment]
I installed the beta with 1 zone and it worked like a dream!   I then enabled 3 more zones and now it's unhappy again.  The device isn't showing at all now, I suspect because it's got confused with the extra zones. Debug log file attached below.  I think we're very close!

[homebridge.log.txt](https://github.com/valiquette/homebridge-orbit-irrigation/files/7658436/homebridge.log.txt)
.

**Comment by valiquette** [comment]
Thanks the log was very helpful. I think I have worked out the big issue with your hardware and multiple zones in 1.0.7-beta.2. it is still hard to test this blind. Especially the test case it you try and start more than one zone at a time.  :et me know how this one works.

**Comment by jase-melbourne** [comment]
Thanks heaps.  I've just installed it and so far so good in terms of a clean startup and finding all the zones.  I'll have a play later on to see how it responds with zones being started/stopped and will let you know.

**Comment by jase-melbourne** [comment]
Hi again!  It's so close! I let the watering go through it's morning programme today and noticed that 3 of the 4 zones is still showing as activated even though they've all turned off.  It looks like the last one to finish has been flagged as stopped but not the first 3.  Is it because the way the programme triggers the start of each zone but only the end of the last one in the sequence? 

Screen shot and log files are below.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/95510918/145101972-4c5fbcb2-2c82-4a69-8839-797c36ba234e.png"

[homebridge.log.txt](https://github.com/valiquette/homebridge-orbit-irrigation/files/7671449/homebridge.log.txt)
>

**Comment by valiquette** [comment]
I was afraid of that, orbit includes the zone or station number when they start but not when the stop, I do not know what order they arrive in or if they are sent, you may be correct on the program schedule. I think I can just force that anytime a new zone starts.  The log does not really have what I would need. If it is possible could you turn debug back on, then truncate the log so it is clean. then run your schedule again?

**Comment by jase-melbourne** [comment]
Sure, no problem at all!  And thanks again for helping me with this.

I setup a test programme and ran it through by skipping to the next zone so I didn't have to wait so long.  Logs are attached. 

It looks like you get a message to start the watering for the selected programme on station 1, then you get a start message for each new station without an end message for the previous one.  When the last station finishes you get a watering complete message.

[homebridge.log.txt](https://github.com/valiquette/homebridge-orbit-irrigation/files/7672730/homebridge.log.txt)

**Comment by valiquette** [comment]
beta 3 posted, fingers crossed.

**Comment by valiquette** [comment]
My bad, beta3 works if the schedules are exposed in the plugin, which is how I was testing it. If not exposed they were throwing that error. beta 4 should work either way.

**Comment by jase-melbourne** [comment]
Good news! It worked beautifully!  I let it run the normal morning watering schedule and watched the zones flick on and off in order.   Snippet from log file is below.  Thank you so much for getting this to work.

[10/12/2021, 06:00:02] [B-Hyve] Running Program a
[10/12/2021, 06:00:02] [B-Hyve] Device Hyve Water Timer, Backyard Grass zone watering in progress for 15 mins
[10/12/2021, 06:10:36] [Ring] Front Door Detected Motion. Loading snapshot before sending event to HomeKit
[10/12/2021, 06:15:03] [B-Hyve] Running Program a
[10/12/2021, 06:15:03] [B-Hyve] Device Hyve Water Timer, Backyard Grass zone watering completed
[10/12/2021, 06:15:03] [B-Hyve] Device Hyve Water Timer, Backyard Courtyard zone watering in progress for 10 mins
[10/12/2021, 06:25:03] [B-Hyve] Running Program a
[10/12/2021, 06:25:03] [B-Hyve] Device Hyve Water Timer, Backyard Courtyard zone watering completed
[10/12/2021, 06:25:03] [B-Hyve] Device Hyve Water Timer, Backyard NorthWest zone watering in progress for 10 mins
[10/12/2021, 06:35:03] [B-Hyve] Running Program a
[10/12/2021, 06:35:03] [B-Hyve] Device Hyve Water Timer, Backyard NorthWest zone watering completed
[10/12/2021, 06:35:03] [B-Hyve] Device Hyve Water Timer, Backyard East zone watering in progress for 10 mins
[10/12/2021, 06:35:07] [Ring] Snapshot for Garage (cocoa_camera - Stick Up Cam) failed to refresh after 70 attempts.  This is normal behavior since this camera is unable to capture snapshots while streaming
[10/12/2021, 06:45:03] [B-Hyve] Device Hyve Water Timer, Backyard East zone watering completed
