### ISSUE TITLE
Node.Js version

### ISSUE THREAD

**Issue by vascott1** [valiquette/homebridge-orbit-irrigation#91]
Trying to get this plugin working and getting this:

17/15/2024, 4:12:08 PM] ---
17/15/2024, 4:12:08 PM] The plugin "homebr idge-orbit-irrigation" requires Node js ve Ision of ^18.20.011 ^20.14.0 |1 ^22.3.0 W hich does not satisfy the current Node.js version of 20.12.2. You may need to upgra de your installation of Node.js - see http s://homebridge.io/w/JTKEF
17/15/2024, 4:12:08 PM] Disabled plugin: h omebridge-orbit-irrigation@1.2.32

No idea why the plugin needs a minor version change from x.12->x.14

Any suggestions? Not sure I want to do a node upgrade for this..

Thanks!

**Comment by valiquette** [comment]
Updating node is pretty simple and keeping current is good.
You can do this within home bridge or terminal, with "sudo hb-service update-node"

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js/

**Comment by vascott1** [comment]
ok. I figured out how to make it work.. The issue I am seeing may or may
not be because of the node version. Hoping I can use this as I at the mercy
of the Docker image.

Thanks!!

---- Errors as child bridge -----

[7/16/2024, 9:40:00 AM] [B-Hyve] Starting Orbit Platform using homebridge
API 2.7
[7/16/2024, 9:40:00 AM] [B-Hyve] Getting Account info...
Error: listen EADDRINUSE: address already in use :::45020
    at Server.setupListenHandle [as _listen2] (node:net:1897:16)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2037:7)
    at EventedHTTPServer.listen
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:166:20)
    at HAPServer.listen
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:380:21)
    at Bridge.<anonymous>
(/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1378:18)
    at step
(/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next
(/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at
/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[7/16/2024, 9:40:00 AM] [B-Hyve] Child bridge process ended
[7/16/2024, 9:40:00 AM] [B-Hyve] Process Ended. Code: 1, Signal: null

--- removing child bridge settings ---

I get this error and Homebridge does not start...

[7/16/2024, 9:45:38 AM] [B-Hyve] Skipping Irrigation System HT34-0001 She’d
based on config
[7/16/2024, 9:45:38 AM] Error: homebridge-orbit-irrigation - bhyve attempt
to register an accessory that isn't PlatformAccessory!
    at /homebridge/node_modules/homebridge/src/api.ts:333:15
    at Array.forEach (<anonymous>)
    at HomebridgeAPI.registerPlatformAccessories
(/homebridge/node_modules/homebridge/src/api.ts:330:17)
    at
/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:591:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/16/2024, 9:45:38 AM] Got SIGTERM, shutting down Homebridge...
[7/16/2024, 9:45:38 AM] Got SIGTERM, shutting down child bridge process...
[7/16/2024, 9:45:38 AM] Got SIGTERM, shutting down child bridge process...

**Comment by valiquette** [comment]
Nothing you can do but ignore the warning. Have you tried to pull the latest docker image?

I also run under docker and always use the hb-service update, never had any issue at all

**Comment by vascott1** [comment]
I can see what the latest image contains. Can't ignore the error as it
stups HB from running..

Are you running normal or as a child bridge? just curious.

Thanks for the fast response :)

**Comment by valiquette** [comment]
Child bridge

**Comment by vascott1** [comment]
hi there, again... I am upgraded to Node 20.15 and started the plugin (v1.2.32)as a child bridge. it starts looping with the following.. hopefully something that can be resolved?

[7/17/2024, 5:15:33 PM] [B-Hyve] Launched child bridge with PID 670
[7/17/2024, 5:15:33 PM] Registering platform 'homebridge-orbit-irrigation.bhyve'
[7/17/2024, 5:15:33 PM] [B-Hyve] Loaded homebridge-orbit-irrigation v1.2.32 child bridge successfully
[7/17/2024, 5:15:33 PM] [B-Hyve] Starting Orbit Platform using homebridge API 2.7
[7/17/2024, 5:15:33 PM] [B-Hyve] Getting Account info...
[7/17/2024, 5:15:33 PM] Homebridge v1.8.3 (HAP v0.12.2) (B-Hyve) is running on port 59154.
[7/17/2024, 5:15:33 PM] [B-Hyve] Found account for Scott Seller
[7/17/2024, 5:15:33 PM] [B-Hyve] Online device BH1-0001 WiFi Hub found at the configured location address: 
[7/17/2024, 5:15:33 PM] [B-Hyve] Online device BH1G2-0000 Wi-Fi Hub Gen 2 found at the configured location address: 
[7/17/2024, 5:15:33 PM] [B-Hyve] Online device HT25-0000 Smart Hose Tap Timer found at the configured location address: 
[7/17/2024, 5:15:33 PM] [B-Hyve] Online device HT34-0001 Shed found at the configured location address:
Error: homebridge-orbit-irrigation - bhyve attempt to register an accessory that isn't PlatformAccessory!
    at /homebridge/node_modules/homebridge/src/api.ts:333:15
    at Array.forEach (<anonymous>)
    at HomebridgeAPI.registerPlatformAccessories (/homebridge/node_modules/homebridge/src/api.ts:330:17)
    at /homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:591:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/17/2024, 5:15:34 PM] [B-Hyve] Child bridge process ended
[7/17/2024, 5:15:34 PM] [B-Hyve] Process Ended. Code: 1, Signal: null

**Comment by valiquette** [comment]
I will take a look, I have test this with the HT25 and HT32 but not the HT34 although I doubt that is an issue here. It would be very helpful to enable debug logging in homebridge and in the plugin config enable logging for the API responses.
and attach the output intron of the plugin crash like you did above. Also can you attach your config for this plugin?

**Comment by vascott1** [comment]
I will do that and enable the debug logging and post the results. Thanks!
  
  
  
  
  
  
  

  
  
>

**Comment by vascott1** [comment]
That was it. Once I disabled the WiFi hub it came right up as a child bridge. Thanks!
  
  
  
  
  
  
  

  
  
>

**Comment by valiquette** [comment]
I was able to reproduce the error, and the underlying issue is now corrected in 1.2.33. That said there is no real reason to expose that device in homekit anyhow, I would leave the setting false. But if you can verify it and close the case if it is resolved I would appreciate that.

**Comment by vascott1** [comment]
corrected in 1.2.33 Thanks again
