### ISSUE TITLE
Crashing Homebridge

### ISSUE THREAD

**Issue by bbobak86** [valiquette/homebridge-orbit-irrigation#93]
Ever since this plugin has been marked "Ready for V2" of Homebridge, its crashing Homebridge. 

06/09/2024, 13:31:59] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/ws/lib/websocket.js:299:7)
    at ReconnectingWebSocket._disconnect (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:539:22)
    at ReconnectingWebSocket._handleError (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:180:19)
    at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:14)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[06/09/2024, 13:31:59] Got SIGTERM, shutting down Homebridge...
[06/09/2024, 13:31:59] [B-Hyve] Opps ErrorEvent {
  target: ReconnectingWebSocket {
    _listeners: { error: [], message: [Array], open: [], close: [] },
    _retryCount: 1,
    _shouldReconnect: true,
    _connectLock: true,
    _binaryType: 'blob',
    _closeCalled: false,
    _messageQueue: [
      '{\n  "event": "sync",\n  "device_id": "6324e15d4f0c968546b79c1a"\n}'
    ],
    onclose: [Function (anonymous)],
    onerror: [Function (anonymous)],
    onmessage: [Function (anonymous)],
    onopen: [Function (anonymous)],
    _handleOpen: [Function (anonymous)],
    _handleMessage: [Function (anonymous)],
    _handleError: [Function (anonymous)],
    _handleClose: [Function (anonymous)],
    _url: 'wss://api.orbitbhyve.com/v1/events',
    _protocols: [],
    _options: {
      WebSocket: [Function],
      maxReconnectionDelay: 10000,
      minReconnectionDelay: 2958.200525588663,
      reconnectionDelayGrowFactor: 1.3,
      minUptime: 5000,
      connectionTimeout: 4000,
      maxRetries: Infinity,
      maxEnqueuedMessages: 1,
      startClosed: false,
      debug: false
    },
    send: [Function (anonymous)],
    _ws: WebSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _binaryType: 'blob',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: <Buffer >,
      _closeTimer: null,
      _errorEmitted: true,
      _extensions: {},
      _paused: false,
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _autoPong: true,
      _url: 'wss://api.orbitbhyve.com/v1/events',
      _req: [ClientRequest],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    _connectTimeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 9882,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 1255,
      [Symbol(triggerId)]: 0
    }
  },
  type: 'error',
  message: 'TIMEOUT',
  error: Error: TIMEOUT
      at ReconnectingWebSocket._handleTimeout (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
      at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)
}
[06/09/2024, 13:31:59] TypeError: Cannot read properties of undefined (reading 'send')
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitapi.js:342:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by bbobak86** [comment]
100% Confirmed its this plugin. Disabled and issues went away.

**Comment by valiquette** [comment]
I can't replicate this, this is also not an area of code that needed any update for HB2.0.  Did you try this on the previous version of code? 
Can you enable debug logging and turn on all the debug options in the plugin and send me what is going on just before the crash. 
The closed before connection opened in the past has been a network issue, but will need logs to figure out

**Comment by bbobak86** [comment]
I’ve tried a bunch of the older releases. I think I went back three or four versions. Nothing on my end has changed regarding configuration. I’ve had the plugin for a few months now and it’s worked flawless. 

I’ll toss this in here, wouldn’t think it would matter but  the timing is similar. I’m running AD Guard through home bridge on my Ras PI now. I don’t see anything in those logs blocking this. 

I enabled all the debugging options and I pulled the following info from the plugins log. If that isn’t correct, please let me know. 

[06/09/2024, 18:46:21] [B-Hyve] Initializing bhyve platform...
[06/09/2024, 18:46:21] [B-Hyve] Starting Orbit Platform using homebridge API 2.7
[06/09/2024, 18:46:21] [B-Hyve] Getting Account info...
[06/09/2024, 18:46:22] [B-Hyve] Found account for Bryan
[06/09/2024, 18:46:22] [B-Hyve] Online device BH1-0001 Wi-Fi Hub found at the configured location address: xxxxxx
[06/09/2024, 18:46:22] [B-Hyve] Online device HT25-0000 Front Yard found at the configured location address: xxxxx
[06/09/2024, 18:46:22] [B-Hyve] Online device HT25-0000 Back Yard - Side found at the configured location address: xxxxxxx
[06/09/2024, 18:46:22] [B-Hyve] Online device HT25-0000 Back Yard - Main found at the configured location address: xxxxxxx
[06/09/2024, 18:46:23] [B-Hyve] Orbit Platform finished loading
[06/09/2024, 18:46:27] [B-Hyve] Skipping Bridge BH1-0001 Wi-Fi Hub based on config
[06/09/2024, 18:46:28] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/09/2024, 18:46:28] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/09/2024, 18:46:28] Got SIGTERM, shutting down Homebridge...
[06/09/2024, 18:46:28] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/09/2024, 18:46:46] [B-Hyve] Initializing bhyve platform...
[06/09/2024, 18:46:46] [B-Hyve] Starting Orbit Platform using homebridge API 2.7
[06/09/2024, 18:46:46] [B-Hyve] Getting Account info...
[06/09/2024, 18:46:47] [B-Hyve] Found account for Bryan
[06/09/2024, 18:46:47] [B-Hyve] Online device BH1-0001 Wi-Fi Hub found at the configured location address: xxxxx
[06/09/2024, 18:46:47] [B-Hyve] Online device HT25-0000 Front Yard found at the configured location address: xxxxxx
[06/09/2024, 18:46:47] [B-Hyve] Online device HT25-0000 Back Yard - Side found at the configured location address: xxxxx
[06/09/2024, 18:46:47] [B-Hyve] Online device HT25-0000 Back Yard - Main found at the configured location address: xxxxx
[06/09/2024, 18:46:47] [B-Hyve] Orbit Platform finished loading
[06/09/2024, 18:46:52] [B-Hyve] Skipping Bridge BH1-0001 Wi-Fi Hub based on config
[06/09/2024, 18:46:52] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/09/2024, 18:46:52] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/09/2024, 18:46:52] Got SIGTERM, shutting down Homebridge...
[06/09/2024, 18:46:52] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:495:11)
    at new PlatformAccessory (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:72:9)
    at valve.createValveAccessory (/var/lib/homebridge/node_modules/homebridge-orbit-irrigation/devices/valve.js:23:24)
    at /var/lib/homebridge/node_modules/homebridge-orbit-irrigation/orbitplatform.js:187:38
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by valiquette** [comment]
You need to enable debug logging in homebridge settings.
This is a different error than the one attached earlier. What version of the plug was this log taken from ?
This looks like the API response back is missing some key info, not sure why. 
This error is API related and other one was Websocket both network so may you don't dismiss Ad guard. Is there any way to disable that service? is it in docker where you can pause it?

**Comment by bbobak86** [comment]
Sorry, forgot I had one of the older updates still running when I ran that log. I updated it then downloaded the log with it running. Let me scrub the private data and I’ll post. 

I did disable ADGuard just now, still same result though.

**Comment by valiquette** [comment]
this error was corrected in 1.2.32  see closed issue #65. Why you are seeing this now is confusing. This may have been ok until the cached accessories were removed and it is trying to build them new. I suspect there is something missing in the response you get back from bhyve.
when you get debug logging running I would be interested in the 'get device response' for one of you hose timers the key part will look like this. The device name and the zone name are important.
Have you tried removing a single cached accessory and if any of these devices are there, remove them.

  "weather_forecast_location_id": "5d1bc1a04f0c6609f63dbff0",
  "firmware_version": "0041",
  "name": "Box Garden",
  "flume_device_id": "",
  "type": "sprinkler_timer",
  "manual_preset_runtime_sec": 600,
  "battery": {
    "percent": 2,
    "charging": false,
    "mv": 2906,
    "low_battery_at": "2023-09-18T09:19:46.000Z"
  },
  "restricted_frequency": null,
  "weather_delay_thresholds": {
    "precip_prob": 30,
    "precip_in": 0.125,
    "wind_speed_mph": 20,
    "freeze_temp_f": 37
  },
  "updated_at": "2024-09-07T09:42:48.414Z",
  "reference": "446755272902-49384",
  "mac_address": "4467551766e7",
  "weather_station_id": "64544aa53c8ad37996d56624",
  "mesh_id": "61354e044f0c6f063b7f2a76",
  "status": {
    "run_mode": "off",
    "next_start_programs": [
      "b"
    ],
    "rain_sensors": [],
    "rain_delay_overridden_at": "2023-09-22T11:14:02.796Z",
    "rain_delay_suggested_at": "2023-04-17T00:17:11.895Z",
    "rain_delay": 0,
    "last_battery_alarm_at": "2024-02-22T16:13:37.118Z",
    "flow_sensor": null,
    "watering-status": null,
    "next_start_time": "2023-06-16T18:15:00-06:00",
    "rain_delay_started_at": "2024-03-29T04:04:16.000Z"
  },
  "id": "61354f6a4f0c6f063b7f2a92",
  "num_stations": 1,
  "zones": [
    {
      "station": 1,
      "slope_grade": 0,
      "sun_shade": "full_sun",
      "name": "Vegetables",
      "landscape_type": "cool_season_turf",
      "drought_level": null,
      "num_sprinklers": 3,
      "soil_type": "clay",
      "catch_cup_volumes": [],
      "catch_cup_run_time": 0,
      "smart_watering_enabled": false,
      "sprinkler_type": "spray",
      "flow_data": {
        "cycle_run_time_sec": 18.625999927520752,
        "flow_rate_gpm": 3.6582252692550954,
        "cycle_volume_gal": 1.1356350599999998
      }
    }
  ],
  "user_id": "61354d0d4f0cf51668e82392",
  "notified_disconnected_at": "2024-09-07T09:42:48.414Z",
  "google_home_status": null,
  "device_gateway_topic": "devices-3",
  "hardware_version": "HT25-0000",
  "is_connected": false,
  "location": {
    "type": "Point",
    "coordinates": [
      -105.4294339,
      39.8117927
    ]
  },
  "created_at": "2021-09-05T23:14:50.915Z",
  "suggested_start_time": null,
  "et_id": "5644ff05ad27a7777ff69e72"
}

**Comment by bbobak86** [comment]
Sorry for the long delay. I’ve been playing around with this and I’m convinced AdGaurd is causing issues. 

Restart plugin with AdGaurd on, it goes crazy and won’t stop. Disable AdGaurd it goes crazy for a couple minutes than stabilizes and works flawless. You can then start AdGaurd back up and everything is fine. Right now I have it running and it stable. But if I restart homebridge, I have to disable AdGaurd temporarily to get it going.

**Comment by valiquette** [comment]
Does the plugin still crash, I would like to address that error if it does.

Can you have ad guard ignore the these address? or "*.orbitbhyve.com". By the sounds of it, the first one is the one with an issue, that is used to get the initial info, after that everything goes through the web socket.
https://api.orbitbhyve.com/v1
wss://api.orbitbhyve.com/v1/events

**Comment by bbobak86** [comment]
It does NOT crash after I disable AdGaurd. Yes I can add to the whitelist or do not block list. I’m going add both of these now.
